name: Python Workflow

on:
  pull_request:
    branches:
      - main

  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  python_only:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

    - name: Check with pylint
      if: always()
      run: |
        pylint --recursive=y .

    - name: Test with pytest
      if: always()
      run: |
        python -m pytest .
